import type { EventoRiesgo, Gravedad } from '@/lib/insforge/types';

// Realistic mock risk events across Pereira neighborhoods
export const MOCK_EVENTOS: (EventoRiesgo & { barrio: string })[] = [
    {
        id: 'evt-001',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Deslizamiento',
        fecha_hora: '2026-02-27T14:30:00',
        descripcion: 'Deslizamiento de tierra afectó 3 viviendas en la ladera. Se reportan 12 personas evacuadas.',
        gravedad: 'Critica',
        coordenadas_lat: 4.8210,
        coordenadas_lng: -75.7050,
        estado_flujo: 'En Verificación',
        barrio: 'Villa Santana',
    },
    {
        id: 'evt-002',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Inundación',
        fecha_hora: '2026-02-27T09:15:00',
        descripcion: 'Desbordamiento parcial del Río Consota por lluvias intensas. Nivel del río al 85%.',
        gravedad: 'Alta',
        coordenadas_lat: 4.8050,
        coordenadas_lng: -75.7120,
        estado_flujo: 'Atendido',
        barrio: 'Cuba',
    },
    {
        id: 'evt-003',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Incendio',
        fecha_hora: '2026-02-26T18:45:00',
        descripcion: 'Incendio forestal de mediana magnitud en zona periurbana. Bomberos controlaron en 3 horas.',
        gravedad: 'Alta',
        coordenadas_lat: 4.8300,
        coordenadas_lng: -75.6800,
        estado_flujo: 'Cerrado',
        barrio: 'Cerritos',
    },
    {
        id: 'evt-004',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Vendaval',
        fecha_hora: '2026-02-26T07:20:00',
        descripcion: 'Vendaval derribó árboles y afectó techos en 5 viviendas. Sin heridos reportados.',
        gravedad: 'Media',
        coordenadas_lat: 4.8160,
        coordenadas_lng: -75.6880,
        estado_flujo: 'Cerrado',
        barrio: 'El Poblado',
    },
    {
        id: 'evt-005',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Deslizamiento',
        fecha_hora: '2026-02-25T16:00:00',
        descripcion: 'Movimiento de masa menor en talud de la vía. Se recomienda monitorear.',
        gravedad: 'Baja',
        coordenadas_lat: 4.7980,
        coordenadas_lng: -75.6990,
        estado_flujo: 'Reportado',
        barrio: 'San Joaquín',
    },
    {
        id: 'evt-006',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Inundación',
        fecha_hora: '2026-02-25T11:30:00',
        descripcion: 'Inundación localizada por taponamiento de alcantarillado en zona céntrica.',
        gravedad: 'Media',
        coordenadas_lat: 4.8133,
        coordenadas_lng: -75.6961,
        estado_flujo: 'Atendido',
        barrio: 'Centro',
    },
    {
        id: 'evt-007',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Sismo',
        fecha_hora: '2026-02-24T03:12:00',
        descripcion: 'Sismo de magnitud 3.2 Ml. Epicentro a 8km al SW de Pereira. Sin daños reportados.',
        gravedad: 'Baja',
        coordenadas_lat: 4.7900,
        coordenadas_lng: -75.7200,
        estado_flujo: 'Cerrado',
        barrio: 'Dosquebradas (zona influencia)',
    },
    {
        id: 'evt-008',
        fk_org: 'org-pereira',
        fk_usuario_reporta: 'demo-001',
        tipo_evento: 'Deslizamiento',
        fecha_hora: '2026-02-27T16:45:00',
        descripcion: 'Socavación en borde de vía terciaria. Tránsito restringido. CARDER notificada.',
        gravedad: 'Critica',
        coordenadas_lat: 4.8350,
        coordenadas_lng: -75.7150,
        estado_flujo: 'Reportado',
        barrio: 'Tokio',
    },
];

export const GRAVEDAD_COLORS: Record<Gravedad, string> = {
    Critica: '#EF4444',
    Alta: '#F97316',
    Media: '#FBBF24',
    Baja: '#10B981',
};

export const ESTADO_LABELS: Record<string, string> = {
    'Reportado': '📋 Reportado',
    'En Verificación': '🔍 En Verificación',
    'Atendido': '✅ Atendido',
    'Cerrado': '🔒 Cerrado',
};
